# 设备OTA的bin文件地址
DEVICES_UPDATE_BIN_PATH: files/devices/ota

# mysql 配置
SQLALCHEMY_DATABASE_URI: mysql://whose:kunshao@127.0.0.1:3306/subordinate?charset=utf8mb4
SQLALCHEMY_COMMIT_ON_TEARDOWN: true
SQLALCHEMY_TRACK_MODIFICATIONS: true
SQLALCHEMY_POOL_RECYCLE: 1800
SQLALCHEMY_ENGINE_OPTIONS:
  pool_pre_ping: true

# 邮箱配置
MAIL_SERVER: smtp.qq.com
MAIL_PORT: 465
MAIL_USE_SSL: true
MAIL_USERNAME: kt_network@qq.com
MAIL_PASSWORD: tkqcyxgdaisiddjh
MAIL_DEFAULT_SENDER: kt_network@qq.com

# redis配置
REDIS_URL: redis://:kunshao@127.0.0.1:6379/0

# mqtt配置
MQTT_BROKER_URL: '192.168.1.150'
MQTT_BROKER_PORT: 1883
MQTT_USERNAME: 'services'
MQTT_PASSWORD: '123456'
MQTT_KEEPALIVE: 5
MQTT_TLS_ENABLED: false
MQTT_CLIENT_ID: 'services'


# 消息队列配置
RABBITMQ_HOST: '127.0.0.1'
RABBITMQ_USERNAME: 'whose'
RABBITMQ_PASSWORD: '123456'
RABBITMQ_VIRTUAL_HOST: '/whose/server'
RABBIT_DELAY_MSG_MODE: 'plugins'
RABBIT_EXCHANGE: 'whose-ks-delay-test-exc'
RABBIT_QUEUE: 'whose-ks-delay-test-que'
